package com.example.asynchronousprogramming.blockingvsunblocking


fun main(){
    val start_time = System.currentTimeMillis()
    val word = "Tweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondigingTweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespra-akskrywerspersverklaringuitreikingsmediakonferensieaankondiging"
    repeat(100_000) {
        removeLetterA(word)
    }
    println(System.currentTimeMillis()-start_time)
}


fun removeLetterA(stringWithLetterA:String): String {
   var stringWithOutLetterA = stringWithLetterA.replace("a", "")
    stringWithOutLetterA = stringWithOutLetterA.replace("A", "")
    return stringWithOutLetterA
}